# With debugging true, there will be a lot of console spam and chat spam to everyone with the permission "antixray.debug". I recommend keeping this false.
Debug: false

# This is the MAX time in ticks (1s = 20 ticks) where if the player mines the Threshold amount of ores (defined below) inside this time,
# they will be flagged up as maybe using xray. If they do not mine the threshold number of ores in this time, they won't be flagged.
Scanning-Time: 1200 #1200 ticks = 60 seconds

# If this amount of ores is broken in the Scanning-Time set above, they will be flagged as maybe using xray. With the default values,
# it is basically saying "if a player mines 6 of the ores defined below in under 60 seconds, flag them as maybe using xray".
Threshold: 6

# These blocks are what the plugin looks for when checking if someone could be using xray.
Ores:
  - DIAMOND_ORE
  - EMERALD_ORE
  - ANCIENT_DEBRIS

# Worlds in this list will not flag anyone for possible xray
World-Blacklist:
  - world1
  - world2
  - world3

# If this is false, players in creative mode will not get flagged for possible xray. It is recommended to keep this false
CheckCreative: false

# Set the alert message that is sent to all players with the "xray.alerts" permission. You can use the following placeholders:
#   %player% - Returns the player suspected of xraying
#   %world% - Returns the name of the world the player is possibly xraying in
#   %xcord% - Returns the X-cord of the location the player is possibly xraying
#   %ycord% - Returns the Y-cord of the location the player is possibly xraying
#   %zcord% - Returns the Z-cord of the location the player is possibly xraying
AlertMessage: "&c%player% might be using xray at %world%: %xcord%, %ycord%, %zcord%"

# This is a fun feature to troll xrayers. If you you have this enabled then you are able to do /axtroll add [player].
# If a player is added to the troll list, then whenever they mine a block from the "Ores:" section above, it will drop
# what you set the "Drop:" item to below instead of the usual drops. To stop trolling them, simply use /axtroll remove [player].
# If "RemoveOnLogout" is set to true, then when a player logs out, it will automatically remove them from the troll list so
# you don't have to. When they rejoin they will not be getting trolled anymore.
TrollCommand:
  Enabled: false
  Drop: COAL
  RemoveOnLogout: true